name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We appreciate your input.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've also thought about...
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Target Platform
      description: Which platform(s) should this feature support?
      multiple: true
      options:
        - All platforms
        - Android
        - iOS
        - Desktop (JVM)
        - Web (JS)
        - Web (WASM)
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: This would help me...
    validations:
      required: false

  - type: textarea
    id: code-example
    attributes:
      label: Example API (Optional)
      description: If you have an idea of how the API should look, please share it here
      render: kotlin
      placeholder: |
        // Example of how you envision using this feature
        val flag = FireAndForget(...)
        flag.newMethod()
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false
