name: Question
description: Ask a question about using FireAndForget
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! We're here to help.

        Before asking, please check:
        - [README](https://github.com/alorma/FireAndForget/blob/main/README.md)
        - [Existing Issues](https://github.com/alorma/FireAndForget/issues)
        - [Discussions](https://github.com/alorma/FireAndForget/discussions) (if enabled)

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about what you're trying to achieve
      placeholder: I'm trying to implement...
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) are you working with?
      multiple: true
      options:
        - Android
        - iOS
        - Desktop (JVM)
        - Web (JS)
        - Web (WASM)
        - Not platform-specific
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: Code Sample (Optional)
      description: If relevant, share the code you're working with
      render: kotlin
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might help us answer your question
    validations:
      required: false
